@startuml
!pragma layout smetana
'https://plantuml.com/object-diagram
'Classes
Class Main
Class Building
Class Room

'Main objects

'Main methods
Main : + static void Main(String[])
Main : + static int countLampsInBuilding(Building)
Main : + static boolean isNormal(Building)

'Room instance variables
Room : - int numberOfDoors
Room : - int numberOfLamps
Room : - int numberOfWindows
'Room constructor
Room : + Room(int, int, int)
'Room methods
Room : + int getNumberOfDoors()
Room : + int getNumberOfLamps()
Room : + int getNumberOfWindows()

'Building instance variables
Building : - ArrayList<Room> rooms
Building : - int numberOfBathrooms
Building : - int numberOfFloors
Building : - boolean isOfficeBuilding
'Building constructor
Building : + Building(ArrayList<Room>, int, int, boolean)
'Building methods
Building : + ArrayList<Room> getRooms()
Building : + int getNumberOfFloors()
Building : + int getNumberOfBathrooms()
Building : + boolean getIsOfficeBuilding()

Main *-- Room
Main *-- Building
Building *-- Room



object Room1
Room1 : numberOfDoors = 1

@enduml
